# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: ghost
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '(?i)\breadme\b'
brews:
  -
    name: ghost
    tap:
      owner: ghost-language
      name: homebrew-ghost
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "https://github.com/ghost-language/ghost."
    dependencies:
      - git
      - zsh
    install: |
      bin.install "ghost"
